export const BACKEND_MESSAGE_CODES = [
  'AUTH_MISSING_TOKEN',
  'AUTH_INVALID_TOKEN',
  'AUTH_PROFILE_REQUIRED',
  'AUTH_USER_NOT_FOUND',
  'AUTH_DISPLAY_NAME_REQUIRED',
  'AUTH_DISPLAY_NAME_TAKEN',
  'AUTH_PROFILE_SAVE_FAILED',
  'AUTH_ACCOUNT_DELETE_FAILED',
  'AUTH_INVALID_REACTION_TYPE',
  'AUTH_INVALID_EMOJI',
  'AUTH_INVALID_LOCALE',
  'AUTH_INVALID_HAPTICS_ENABLED',
  'AUTH_INVALID_DISCARD_PILE_PREFERENCE',
  'AUTH_INVALID_SUIT_DISPLAY_MODE',
  'AUTH_INVALID_ROLE',
  'AUTH_ROLE_ASSIGNMENT_NOT_ALLOWED',
  'ROOM_NOT_FOUND',
  'ROOM_ACCESS_DENIED',
  'ROOM_FULL',
  'ROOM_INVALID_CREATE_REQUEST',
  'ROOM_HOST_LIMIT_REACHED',
  'ROOM_ONLY_HOST_REMOVE_BOTS',
  'ROOM_ONLY_HOST_RENAME_BOTS',
  'ROOM_BOT_NOT_FOUND',
  'ROOM_BOT_NAME_TAKEN',
  'ROOM_INVALID_BOT_NAME',
  'ROOM_REMOVE_BOT_ONLY',
  'ROOM_ONLY_HOST_KICK_PLAYERS',
  'ROOM_CANNOT_KICK_SELF',
  'ROOM_PLAYER_NOT_FOUND',
  'ROOM_ONLY_HOST_REORDER_PLAYERS',
  'ROOM_REORDER_WAITING_ONLY',
  'ROOM_RENAME_BOT_WAITING_ONLY',
  'ROOM_ONLY_HOST_UPDATE_OPTIONS',
  'ROOM_UPDATE_WAITING_ONLY',
  'ROOM_INVALID_OPTIONS',
  'ROOM_REORDER_PLAYER_IDS_ARRAY',
  'ROOM_REORDER_PLAYER_IDS_INVALID',
  'ROOM_NOT_IN_ROOM',
  'SOCKET_ONLY_HOST_END_GAME',
  'SOCKET_ONLY_HOST_RECREATE_ROOM',
  'SOCKET_CANNOT_DRAW',
  'SOCKET_CANNOT_PASS',
  'SOCKET_CANNOT_APPLY_BRIDGE',
  'SOCKET_CANNOT_DECLINE_BRIDGE',
  'GAME_NOT_ACTIVE',
  'GAME_NOT_YOUR_TURN',
  'GAME_SELECT_CARDS',
  'GAME_CARDS_NOT_IN_HAND',
  'GAME_SAME_RANK_ONLY',
  'GAME_PENALTY_ACTIVE',
  'GAME_CANNOT_FINISH_WITH_SIX',
  'GAME_CHOOSE_SUIT_FOR_JACK',
  'GAME_AFTER_SIX_RULE',
  'GAME_OPENING_TURN_RULE',
  'GAME_ACTIVE_SUIT_RULE',
  'GAME_CARD_MUST_MATCH',
  'GAME_PLAYER_NOT_FOUND',
  'GAME_DEADLOCK_RESOLVED',
  'ROOM_CLOSED_HOST_LEFT',
  'ROOM_CLOSED_IDLE_TIMEOUT',
  'ROOM_CLOSED_DELETED_BY_HOST',
  'ROOM_CLOSED_ENDED_BY_HOST',
  'ROOM_CLOSED_RECREATED_BY_HOST',
  'ROOM_CLOSED_FINISHED',
  'ROOM_DEFAULT_NAME',
  'BOT_DEFAULT_NAME',
] as const;

export type BackendMessageCode = (typeof BACKEND_MESSAGE_CODES)[number];

export type BackendMessageParamsByCode = {
  AUTH_MISSING_TOKEN: undefined;
  AUTH_INVALID_TOKEN: undefined;
  AUTH_PROFILE_REQUIRED: undefined;
  AUTH_USER_NOT_FOUND: undefined;
  AUTH_DISPLAY_NAME_REQUIRED: undefined;
  AUTH_DISPLAY_NAME_TAKEN: undefined;
  AUTH_PROFILE_SAVE_FAILED: undefined;
  AUTH_ACCOUNT_DELETE_FAILED: undefined;
  AUTH_INVALID_REACTION_TYPE: undefined;
  AUTH_INVALID_EMOJI: undefined;
  AUTH_INVALID_LOCALE: undefined;
  AUTH_INVALID_HAPTICS_ENABLED: undefined;
  AUTH_INVALID_DISCARD_PILE_PREFERENCE: undefined;
  AUTH_INVALID_SUIT_DISPLAY_MODE: undefined;
  AUTH_INVALID_ROLE: undefined;
  AUTH_ROLE_ASSIGNMENT_NOT_ALLOWED: undefined;
  ROOM_NOT_FOUND: undefined;
  ROOM_ACCESS_DENIED: undefined;
  ROOM_FULL: undefined;
  ROOM_INVALID_CREATE_REQUEST: undefined;
  ROOM_HOST_LIMIT_REACHED: undefined;
  ROOM_ONLY_HOST_REMOVE_BOTS: undefined;
  ROOM_ONLY_HOST_RENAME_BOTS: undefined;
  ROOM_BOT_NOT_FOUND: undefined;
  ROOM_BOT_NAME_TAKEN: undefined;
  ROOM_INVALID_BOT_NAME: undefined;
  ROOM_REMOVE_BOT_ONLY: undefined;
  ROOM_ONLY_HOST_KICK_PLAYERS: undefined;
  ROOM_CANNOT_KICK_SELF: undefined;
  ROOM_PLAYER_NOT_FOUND: undefined;
  ROOM_ONLY_HOST_REORDER_PLAYERS: undefined;
  ROOM_REORDER_WAITING_ONLY: undefined;
  ROOM_RENAME_BOT_WAITING_ONLY: undefined;
  ROOM_ONLY_HOST_UPDATE_OPTIONS: undefined;
  ROOM_UPDATE_WAITING_ONLY: undefined;
  ROOM_INVALID_OPTIONS: undefined;
  ROOM_REORDER_PLAYER_IDS_ARRAY: undefined;
  ROOM_REORDER_PLAYER_IDS_INVALID: undefined;
  ROOM_NOT_IN_ROOM: undefined;
  SOCKET_ONLY_HOST_END_GAME: undefined;
  SOCKET_ONLY_HOST_RECREATE_ROOM: undefined;
  SOCKET_CANNOT_DRAW: undefined;
  SOCKET_CANNOT_PASS: undefined;
  SOCKET_CANNOT_APPLY_BRIDGE: undefined;
  SOCKET_CANNOT_DECLINE_BRIDGE: undefined;
  GAME_NOT_ACTIVE: undefined;
  GAME_NOT_YOUR_TURN: undefined;
  GAME_SELECT_CARDS: undefined;
  GAME_CARDS_NOT_IN_HAND: undefined;
  GAME_SAME_RANK_ONLY: undefined;
  GAME_PENALTY_ACTIVE: { count: number };
  GAME_CANNOT_FINISH_WITH_SIX: undefined;
  GAME_CHOOSE_SUIT_FOR_JACK: undefined;
  GAME_AFTER_SIX_RULE: { suitName: string };
  GAME_OPENING_TURN_RULE: { rank: string };
  GAME_ACTIVE_SUIT_RULE: { suitName: string };
  GAME_CARD_MUST_MATCH: { suitName: string; rank: string };
  GAME_PLAYER_NOT_FOUND: undefined;
  GAME_DEADLOCK_RESOLVED: undefined;
  ROOM_CLOSED_HOST_LEFT: undefined;
  ROOM_CLOSED_IDLE_TIMEOUT: { minutes: number };
  ROOM_CLOSED_DELETED_BY_HOST: undefined;
  ROOM_CLOSED_ENDED_BY_HOST: undefined;
  ROOM_CLOSED_RECREATED_BY_HOST: undefined;
  ROOM_CLOSED_FINISHED: undefined;
  ROOM_DEFAULT_NAME: { userName: string };
  BOT_DEFAULT_NAME: { index: number };
};
