import type { BackendMessageCode } from './backendMessageDefinitions';
import type { AppLocale } from './i18n';

type BackendMessageTemplateMap = Record<BackendMessageCode, string>;

export const BACKEND_MESSAGE_TEMPLATES: Record<AppLocale, BackendMessageTemplateMap> = {
  uk: {
    AUTH_MISSING_TOKEN: 'Відсутній токен авторизації',
    AUTH_INVALID_TOKEN: 'Невалідний токен',
    AUTH_PROFILE_REQUIRED: 'Потрібно завершити профіль гравця',
    AUTH_USER_NOT_FOUND: 'Користувача не знайдено',
    AUTH_DISPLAY_NAME_REQUIRED: 'Ігрове імʼя є обовʼязковим',
    AUTH_DISPLAY_NAME_TAKEN: 'Ігрове імʼя вже зайняте',
    AUTH_PROFILE_SAVE_FAILED: 'Не вдалося зберегти профіль',
    AUTH_ACCOUNT_DELETE_FAILED: 'Не вдалося видалити акаунт',
    AUTH_INVALID_REACTION_TYPE: 'Невалідний тип реакції',
    AUTH_INVALID_EMOJI: 'Невалідне емоджі',
    AUTH_INVALID_LOCALE: 'Невалідна мова',
    AUTH_INVALID_HAPTICS_ENABLED: 'Невалідне значення для haptic-ефектів',
    AUTH_INVALID_DISCARD_PILE_PREFERENCE: 'Невалідне значення для відображення відбою',
    AUTH_INVALID_ROLE: 'Невалідна роль',
    AUTH_ROLE_ASSIGNMENT_NOT_ALLOWED: 'Цю роль не можна змінювати',
    ROOM_NOT_FOUND: 'Кімнату не знайдено',
    ROOM_ACCESS_DENIED: 'Доступ заборонено',
    ROOM_FULL: 'Кімната заповнена',
    ROOM_INVALID_CREATE_REQUEST: 'Невалідні дані для створення кімнати',
    ROOM_HOST_LIMIT_REACHED: 'Досягнуто ліміт активних кімнат',
    ROOM_ONLY_HOST_REMOVE_BOTS: 'Лише хост може видаляти ботів',
    ROOM_ONLY_HOST_RENAME_BOTS: 'Лише хост може перейменовувати ботів',
    ROOM_BOT_NOT_FOUND: 'Бота не знайдено',
    ROOM_BOT_NAME_TAKEN: 'Це імʼя бота вже зайняте',
    ROOM_INVALID_BOT_NAME: 'Невалідне імʼя бота',
    ROOM_REMOVE_BOT_ONLY: 'Можна видаляти лише ботів',
    ROOM_ONLY_HOST_KICK_PLAYERS: 'Лише хост може видаляти гравців',
    ROOM_CANNOT_KICK_SELF: 'Не можна видалити себе',
    ROOM_PLAYER_NOT_FOUND: 'Гравця не знайдено',
    ROOM_ONLY_HOST_REORDER_PLAYERS: 'Лише хост може змінювати порядок гравців',
    ROOM_REORDER_WAITING_ONLY: 'Порядок гравців можна змінювати лише в стані очікування',
    ROOM_RENAME_BOT_WAITING_ONLY: 'Ботів можна перейменовувати лише в стані очікування',
    ROOM_ONLY_HOST_UPDATE_OPTIONS: 'Лише хост може змінювати налаштування кімнати',
    ROOM_UPDATE_WAITING_ONLY: 'Налаштування можна змінювати лише в стані очікування',
    ROOM_INVALID_OPTIONS: 'Невалідні налаштування кімнати',
    ROOM_REORDER_PLAYER_IDS_ARRAY: '`playerIds` має бути масивом',
    ROOM_REORDER_PLAYER_IDS_INVALID: 'Невалідний перелік ID гравців',
    ROOM_NOT_IN_ROOM: 'Ви не перебуваєте в кімнаті',
    SOCKET_ONLY_HOST_END_GAME: 'Лише хост може завершити гру',
    SOCKET_ONLY_HOST_RECREATE_ROOM: 'Лише хост може перестворити кімнату',
    SOCKET_CANNOT_DRAW: 'Не можна взяти карту',
    SOCKET_CANNOT_PASS: 'Не можна передати хід',
    SOCKET_CANNOT_APPLY_BRIDGE: 'Не можна застосувати міст',
    SOCKET_CANNOT_DECLINE_BRIDGE: 'Не можна відхилити міст',
    GAME_NOT_ACTIVE: 'Гра не активна',
    GAME_NOT_YOUR_TURN: 'Не ваш хід',
    GAME_SELECT_CARDS: 'Оберіть карти для ходу',
    GAME_CARDS_NOT_IN_HAND: 'У вас немає цих карт',
    GAME_SAME_RANK_ONLY: 'Можна класти лише карти одного номіналу',
    GAME_PENALTY_ACTIVE: 'Активний штраф {{count}} карт. Покладіть 7 або візьміть карти',
    GAME_CANNOT_FINISH_WITH_SIX: 'Не можна завершити раунд шісткою. Шістка вимагає ще один хід',
    GAME_CHOOSE_SUIT_FOR_JACK: 'Оберіть масть для валета',
    GAME_AFTER_SIX_RULE: 'Після 6 можна класти лише {{suitName}}, іншу 6, або валета',
    GAME_OPENING_TURN_RULE: 'Перший хід раунду: можна класти лише {{rank}}',
    GAME_ACTIVE_SUIT_RULE: 'Активна масть: {{suitName}}. Кладіть {{suitName}} або валета',
    GAME_CARD_MUST_MATCH: 'Карта має співпадати по масті ({{suitName}}) або номіналу ({{rank}})',
    GAME_PLAYER_NOT_FOUND: 'Гравця не знайдено',
    GAME_DEADLOCK_RESOLVED:
      'Сталася тупикова ситуація (deadlock): один або кілька гравців не мали легального ходу, а добір карт був неможливий. Їхні ходи автоматично пропущено, гра продовжується.',
    ROOM_CLOSED_HOST_LEFT: 'Хост покинув кімнату',
    ROOM_CLOSED_IDLE_TIMEOUT: 'Кімната закрита через неактивність ({{minutes}} хв)',
    ROOM_CLOSED_DELETED_BY_HOST: 'Видалено хостом',
    ROOM_CLOSED_ENDED_BY_HOST: 'Завершено хостом',
    ROOM_CLOSED_RECREATED_BY_HOST: 'Перестворено хостом',
    ROOM_CLOSED_FINISHED: 'Завершено',
    ROOM_DEFAULT_NAME: '{{userName}}',
    BOT_DEFAULT_NAME: 'Bot {{index}}',
  },
  en: {
    AUTH_MISSING_TOKEN: 'Missing authorization token',
    AUTH_INVALID_TOKEN: 'Invalid token',
    AUTH_PROFILE_REQUIRED: 'Player profile setup is required',
    AUTH_USER_NOT_FOUND: 'User not found',
    AUTH_DISPLAY_NAME_REQUIRED: 'Display name is required',
    AUTH_DISPLAY_NAME_TAKEN: 'Display name is already taken',
    AUTH_PROFILE_SAVE_FAILED: 'Failed to save profile',
    AUTH_ACCOUNT_DELETE_FAILED: 'Failed to delete account',
    AUTH_INVALID_REACTION_TYPE: 'Invalid reaction type',
    AUTH_INVALID_EMOJI: 'Invalid emoji',
    AUTH_INVALID_LOCALE: 'Invalid locale',
    AUTH_INVALID_HAPTICS_ENABLED: 'Invalid haptics setting',
    AUTH_INVALID_DISCARD_PILE_PREFERENCE: 'Invalid discard pile display setting',
    AUTH_INVALID_ROLE: 'Invalid role',
    AUTH_ROLE_ASSIGNMENT_NOT_ALLOWED: 'This role cannot be changed',
    ROOM_NOT_FOUND: 'Room not found',
    ROOM_ACCESS_DENIED: 'Access denied',
    ROOM_FULL: 'Room is full',
    ROOM_INVALID_CREATE_REQUEST: 'Invalid room creation payload',
    ROOM_HOST_LIMIT_REACHED: 'Active room limit reached',
    ROOM_ONLY_HOST_REMOVE_BOTS: 'Only the host can remove bots',
    ROOM_ONLY_HOST_RENAME_BOTS: 'Only the host can rename bots',
    ROOM_BOT_NOT_FOUND: 'Bot not found',
    ROOM_BOT_NAME_TAKEN: 'This bot name is already taken',
    ROOM_INVALID_BOT_NAME: 'Invalid bot name',
    ROOM_REMOVE_BOT_ONLY: 'Only bots can be removed',
    ROOM_ONLY_HOST_KICK_PLAYERS: 'Only the host can kick players',
    ROOM_CANNOT_KICK_SELF: 'You cannot kick yourself',
    ROOM_PLAYER_NOT_FOUND: 'Player not found',
    ROOM_ONLY_HOST_REORDER_PLAYERS: 'Only the host can reorder players',
    ROOM_REORDER_WAITING_ONLY: 'Players can only be reordered while waiting',
    ROOM_RENAME_BOT_WAITING_ONLY: 'Bots can only be renamed while waiting',
    ROOM_ONLY_HOST_UPDATE_OPTIONS: 'Only the host can update room options',
    ROOM_UPDATE_WAITING_ONLY: 'Room options can only be updated while waiting',
    ROOM_INVALID_OPTIONS: 'Invalid room options',
    ROOM_REORDER_PLAYER_IDS_ARRAY: '`playerIds` must be an array',
    ROOM_REORDER_PLAYER_IDS_INVALID: 'Invalid player ID list',
    ROOM_NOT_IN_ROOM: 'You are not in this room',
    SOCKET_ONLY_HOST_END_GAME: 'Only the host can end the game',
    SOCKET_ONLY_HOST_RECREATE_ROOM: 'Only the host can recreate the room',
    SOCKET_CANNOT_DRAW: 'Cannot draw a card',
    SOCKET_CANNOT_PASS: 'Cannot pass the turn',
    SOCKET_CANNOT_APPLY_BRIDGE: 'Cannot apply bridge',
    SOCKET_CANNOT_DECLINE_BRIDGE: 'Cannot decline bridge',
    GAME_NOT_ACTIVE: 'Game is not active',
    GAME_NOT_YOUR_TURN: 'It is not your turn',
    GAME_SELECT_CARDS: 'Select cards to play',
    GAME_CARDS_NOT_IN_HAND: 'You do not have these cards',
    GAME_SAME_RANK_ONLY: 'You can only play cards of the same rank',
    GAME_PENALTY_ACTIVE: 'Penalty of {{count}} cards is active. Play a 7 or draw cards',
    GAME_CANNOT_FINISH_WITH_SIX: 'You cannot finish a round with a 6. A 6 requires one more play',
    GAME_CHOOSE_SUIT_FOR_JACK: 'Choose a suit for the jack',
    GAME_AFTER_SIX_RULE: 'After a 6, play only {{suitName}}, another 6, or a jack',
    GAME_OPENING_TURN_RULE: 'Opening turn: only {{rank}} can be played',
    GAME_ACTIVE_SUIT_RULE: 'Active suit: {{suitName}}. Play {{suitName}} or a jack',
    GAME_CARD_MUST_MATCH: 'Card must match suit ({{suitName}}) or rank ({{rank}})',
    GAME_PLAYER_NOT_FOUND: 'Player not found',
    GAME_DEADLOCK_RESOLVED:
      'A deadlock occurred: one or more players had no legal move and drawing cards was impossible. Their turns were skipped automatically, and the game continues.',
    ROOM_CLOSED_HOST_LEFT: 'Host left the room',
    ROOM_CLOSED_IDLE_TIMEOUT: 'Room closed due to inactivity ({{minutes}} min)',
    ROOM_CLOSED_DELETED_BY_HOST: 'Deleted by host',
    ROOM_CLOSED_ENDED_BY_HOST: 'Ended by host',
    ROOM_CLOSED_RECREATED_BY_HOST: 'Recreated by host',
    ROOM_CLOSED_FINISHED: 'Finished',
    ROOM_DEFAULT_NAME: '{{userName}}',
    BOT_DEFAULT_NAME: 'Bot {{index}}',
  },
};
